hoodiehq/hoodie-account-server

- api/accounts/add.js
- api/accounts/find-all.js
- api/accounts/find.js
- api/index.js
- package.json
- plugin/index.js
- routes/account.js
- routes/accounts.js
- routes/session.js
- tests/integration/account-test.js
- tests/integration/accounts-test.js
- tests/integration/fixtures/session-admin-response.json
- tests/integration/fixtures/session-response.json
- tests/integration/fixtures/session-with-profile-response.json
- tests/integration/session-test.js
- utils/account/create.js
- utils/account/get-all.js
- utils/find-custom-roles.js
- utils/has-admin-role.js
- utils/session/create.js
- utils/session/get.js
- utils/session/serialise.js
- utils/to-bearer-token.js
adds `GET /accounts` route for admins. Part of https://github.com/hoodiehq/hoodie-server-account/issues/12
> GET /accounts

- api/accounts/add.js
- api/accounts/find-all.js
- api/accounts/find.js
- api/accounts/remove.js
- api/accounts/update.js
- api/index.js
- package.json
- plugin/README.md
- plugin/couchdb/users-design-doc.js
- plugin/index.js
- routes/account.js
- routes/accounts.js
- tests/integration/account-test.js
- tests/integration/accounts-test.js
- tests/integration/fixtures/account.json
- tests/integration/fixtures/accounts-with-profile.json
- tests/integration/fixtures/accounts.json
- tests/integration/fixtures/admin-account-with-profile.json
- tests/integration/fixtures/admin-account.json
- tests/integration/fixtures/session-response.json
- tests/integration/fixtures/session-with-profile-response.json
- tests/integration/utils/get-server.js
- utils/account/change.js
- utils/account/create.js
- utils/account/delete.js
- utils/account/get-all.js
- utils/account/get.js
- utils/account/serialise.js
- utils/session/serialise.js
> Implement accounts API for admins

- README.md
- api/README.md
- api/accounts/add.js
- api/accounts/find.js
- api/accounts/on.js
- api/accounts/update.js
- api/index.js
- api/utils/start-listening-to-account-changes.js
- bin/watch-and-test.sh
- package.json
- plugin/couchdb/users-design-doc.js
- tests/integration/api/accounts-test.js
- tests/integration/routes/account-test.js
- tests/integration/routes/accounts-test.js
- tests/integration/routes/session-test.js
This PR implements `add` / `update` / `remove` / `change` events for accounts, and the `accounts.on` method
> api.accounts Events

- tests/integration/routes/account-test.js
- tests/integration/routes/session-test.js
> test: remove obsolete tape lines

- package.json
closes #44
closes #46
closes #47
closes #49
> chore(package): updates dependencies

- api/accounts/update.js
- plugin/index.js
- tests/integration/routes/account-test.js
- tests/integration/routes/accounts-test.js
- tests/integration/routes/requests-test.js
- tests/integration/routes/session-test.js
Adhere to new coding style: https://github.com/hoodiehq/hoodie/pull/453
> feat(lodash): use main lodash module

- plugin/index.js
- routes/README.md
- routes/profile.js
- routes/utils/errors.js
- routes/utils/serialise-profile.js
- tests/integration/fixtures/profile.json
- tests/integration/routes/account-test.js
- tests/integration/routes/profile-test.js
> Get session account profile

- routes/profile.js
- routes/utils/validations.js
- tests/integration/routes/profile-test.js
Hi,
I will need some help on the tests if you've got the time. Right now I've got an error ```Missing JSON list of 'docs'```. I think it comes front the fact that I'm not able to properly mock the request to update the account. (And I think, I need to mock 2 times the GET with ```mockUserFound```). Am I right ?
Thanks for your work too ! What a nice community ! :heart_eyes_cat: 
fixes #60
> Update session account profile

- routes/session.js
- routes/utils/errors.js
- tests/integration/routes/session-test.js
> PUT /session to return 401 Unauthorized error when user cannot be found

- routes/account.js
- tests/integration/routes/account-test.js
> 401 responses for /session/account #81

- routes/profile.js
- routes/utils/errors.js
- tests/integration/routes/profile/get-profile-test.js
> test(routes): GET /session/account/profile error for admins

- routes/account.js
- tests/integration/routes/account/patch-account-test.js
> test(routes): PATCH /session/account -> 204

- routes/accounts.js
- tests/integration/routes/accounts/post-accounts-test.js
> test(routes): POST /accounts -> 401 for invalid session

- api/accounts/add.js
- api/utils/errors.js
- tests/integration/routes/account/put-account-test.js
This is my first PR so can somebody assure me that I'm doing it correctly?
I've adjusted the tests to fail with the old error message.
--- 
closes #97
> test(routes): PUT /session/account 409 error message

- routes/accounts.js
- tests/integration/routes/accounts/post-accounts-test.js
> fix(routes): POST /accounts?include=foobar -> 400

- README.md
- api/README.md
- api/utils/errors.js
- how-it-works.md
- package.json
- plugin/README.md
- routes/README.md
- tests/README.md
- tests/integration/routes/account/patch-account-test.js
- tests/integration/routes/accounts/post-accounts-test.js
- tests/integration/routes/profile/patch-profile-test.js
- tests/integration/routes/session/put-session-test.js
> Rename module and repo

- routes/session.js
- tests/integration/routes/session/get-session-test.js
> 404 should be 401 on /session

- plugin/index.js
- plugin/remove-cookie-header.js
- tests/integration/routes/no-cookie-header-test.js
This PR is still WIP as I have failing tests and I would need some feedback. I am also unsure if I have placed the removeCookie plugin into the right folder.
---
fixes #17
> feat(remove-cookies): create plugin,tests and registration

- tests/README.md
> docs(tests): fixed git clone URL

- routes/session.js
- tests/integration/routes/session/put-session-test.js
fixes https://github.com/hoodiehq/hoodie/issues/499
> signin with uppercase letters

- api/README.md
- api/sessions/add.js
- routes/account.js
- routes/accounts.js
- routes/profile.js
- routes/session.js
- routes/utils/request-to-bearer-token.js
- routes/utils/request-to-session-id.js
- routes/utils/validations.js
- tests/integration/routes/account/delete-account-test.js
- tests/integration/routes/account/get-account-test.js
- tests/integration/routes/account/patch-account-test.js
- tests/integration/routes/accounts/delete-accounts-test.js
- tests/integration/routes/accounts/get-accounts-test.js
- tests/integration/routes/accounts/patch-accounts-test.js
- tests/integration/routes/accounts/post-accounts-test.js
- tests/integration/routes/profile/get-profile-test.js
- tests/integration/routes/profile/patch-profile-test.js
- tests/integration/routes/session/delete-session-test.js
- tests/integration/routes/session/get-session-test.js
- tests/integration/utils/authorization-header-not-allowed-error.js
> rename bearer to session

- package.json
- tests/integration/routes/account/delete-account-test.js
- tests/integration/routes/account/patch-account-test.js
- tests/integration/routes/account/put-account-test.js
- tests/integration/routes/accounts/delete-accounts-test.js
- tests/integration/routes/accounts/patch-accounts-test.js
- tests/integration/routes/accounts/post-accounts-test.js
- tests/integration/routes/no-cookie-header-test.js
- tests/integration/routes/profile/patch-profile-test.js
- tests/integration/routes/requests/post-requests-test.js
- tests/integration/utils/get-server.js
> PouchDB@6 updates

- api/accounts/add.js
- package.json
- tests/integration/routes/account/put-account-test.js
- tests/integration/routes/accounts/post-accounts-test.js
This PR (my first, ever) closes hoodiehq/camp#31.
> Changed Account IDs to utilize UUID

- tests/integration/routes/accounts/delete-accounts-test.js
> test(routes): DELETE /accounts/123?include=foobar

- routes/account.js
- routes/utils/serialise-account.js
- tests/integration/fixtures/account.json
- tests/integration/fixtures/accounts-with-profile.json
- tests/integration/fixtures/accounts.json
- tests/integration/fixtures/admin-account-with-profile.json
- tests/integration/fixtures/admin-account.json
- tests/integration/routes/account/get-account-test.js
- tests/integration/routes/account/put-account-test.js
- tests/integration/routes/accounts/get-accounts-test.js
closes hoodiehq/camp#61
@gr2m please review
> feat(routes): signup timestamps

- .gitignore
- routes/utils/errors.js
- routes/utils/serialise-session.js
- tests/unit/errors-test.js
- tests/unit/joi-fail-action-test.js
- tests/unit/request-to-session-id-test.js
- tests/unit/serialise-account-test.js
> Coverage utils

- tests/integration/routes/accounts/patch-accounts-test.js
> test(routes): PATCH /accounts/123 with invalid type / id attributes

- routes/accounts.js
- tests/integration/routes/accounts/patch-accounts-test.js
Note that this test currently fails.
hoodiehq/camp#71
> Add test for invalid include parameter for accounts PATCH.

- routes/accounts.js
- routes/utils/errors.js
- tests/integration/routes/accounts/patch-accounts-test.js
> Test PATCH /accounts/{id} if account not found

- package.json
- routes/account.js
- routes/session.js
- tests/integration/utils/get-server.js
adapts usage of API as documented in https://github.com/hoodiehq/hoodie-account-server-api/releases/tag/v3.0.0
> @hoodie/account-api@3

- package.json
- tests/integration/utils/get-server.js
Addresses hoodiehq/camp#59, but I cannot test it on my system. It'd be great if you could test this, and the current master branch if it works.
> test: replace pouchdb with custom build for testing

- routes/accounts.js
- tests/integration/routes/accounts/patch-accounts-test.js
> test(routes): PATCH /accounts/{id} with invalid session

- routes/accounts.js
- tests/integration/routes/accounts/get-accounts-test.js
> test(routes): GET /accounts/123?include=foobar

- package.json
- tests/integration/routes/account/patch-account-test.js
> @hoodie/account-server-api@3.3.0

- tests/integration/routes/accounts/patch-accounts-test.js
> test(routes): PATCH /accounts/{id} if user is not an admin

- tests/integration/routes/account/get-account-test.js
https://github.com/hoodiehq/camp/issues/53
> wrote test coverage for account.js line 73

- package.json
- routes/utils/validations.js
with code adjustment for new standard style requirements
closes #230
> standard@^8.6.0

- routes/session.js
- tests/integration/routes/session/put-session-test.js
> signin with token

- routes/account.js
- tests/integration/routes/account/delete-account-test.js
starting https://github.com/hoodiehq/camp/issues/77
> test(routes): DELETE /accounts/123?include=profile

- tests/integration/routes/accounts/patch-accounts-test.js
> WIP: test(routes): PATCH /accounts/123?include=profile

- package.json
see https://github.com/kjellmorten/hapi-json-api/commit/bbd135dbe80d818304a86354feaf24196f6d5aa6#commitcomment-25082141
> pin @gar/hapi-json-api to 2.0.3

- .travis.yml
- package.json
also force-update semantic-release
> travis: avoid double builds for PRs

- package.json
> fix(package): update pouchdb-errors to version 6.4.1
